server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route1 # 路由的ID,没有固定规则,唯一即可
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**
        - id: payment_route2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/discovery/**
        - id: payment_route3_lb
          uri:
            lb://CLOUD-PAYMENT-SERVICE # 匹配提供服务的路由地址
          predicates:
            - Path=/payment/test/timeout


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
